### ISSUE TITLE
Version change

### ISSUE THREAD

**Issue by chrisduerr** [zacps/winpty#2]
Since Alacritty has already been using winpty-sys for a long while, the latest change to downgrade the version number has created a few issues.

I believe that change is the source of these build failures:
https://travis-ci.org/jwilm/alacritty/builds/458729357

It's potentially also an issue with a force push to master? You might have destroyed an old commit.

But even if the cache is cleaned, this could lead to future issues with `cargo update` since Alacritty ships the lockfile with a 1.1 version of this library.

**Comment by zacps** [comment]
Whoops, this should hopefully be fixed by moving to a crate.io dep https://github.com/jwilm/alacritty/pull/1838

**Comment by zacps** [comment]
This also reminds me that Alacritty's lockfile isn't especially useful because afaict it gets invalidated every time there's a PR from a different platform because of platform specific deps. It might be worth removing it from git entirely, though not an ideal solution I know.

Edit: Nevermind I took another look and that doesn't seem to be the case

**Comment by chrisduerr** [comment]
@zacps No, the lockfile should be included into Alacritty and that is the idiomatic way to handle this with Rust. That's why it's not in the gitignore by default when running `cargo new project`, but it is in the gitignore when you run `cargo new project --lib`.

Different platforms don't matter for the lockfile either. The lockfile is platform-independent. All dependencies are specified in there, even on Linux if you never use `winapi`, it will still be part of the lockfile.

The smart people at rust-lang/rust have thought this through, so everything's fine the way it is right now.
